image: theimpulson/gitlab-ci-android

variables:
  SECURE_FILES_URL: https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/-/raw/main/installer

cache:
  key:
    files:
      - .Gemfile.lock
  paths:
    - vendor/bundle

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew
  - apt update
  - apt install -y ruby-full ruby-bundler build-essential
  - gem install bundler
  - bundle config set path 'vendor/bundle'
  - bundle check || bundle install --jobs $(nproc)

stages:
  - build
  - test
  - staging
  - deploy

test:
  stage: test
  script:
    - bundle exec fastlane test

build:
  stage: build
  script:
    - bundle exec fastlane debug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk

staging:
  stage: staging
  only:
    - develop
  script:
    - curl -s $SECURE_FILES_URL | bash
    - bundle exec fastlane beta

deploy:
  stage: deploy
  only:
    - main
  script:
    - curl -s $SECURE_FILES_URL | bash
    - bundle exec fastlane deploy