name: build-apk
run-name: Build APK

on:
  push:
    branches:
      - develop

jobs:
    call-setup-fastlane:
        name: Call Setup Fastlane
        uses: rdugue/Phito-Arch/.github/workflows/setup-fastlane.yml@main
    build-apk:
        name: Build APK
        runs-on: ubuntu-latest
        steps:
          - name: Build APK
            run: bundle exec fastlane debug
          - name: Upload APK
            uses: actions/upload-artifact@v3
            with:
              name: app-debug.apk
              path: app/build/outputs/apk/debug/app-debug.apk
              retention-days: 1