name: run-tests
run-name: Run Tests

on:
  push:
    branches:
      - feature/*
      - develop
      - main

jobs:
    call-setup-fastlane:
        name: Call Setup Fastlane
        uses: rdugue/Phito-Arch/.github/workflows/setup-fastlane.yml@main
    run-tests:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
          - name: Run tests
            run: bundle exec fastlane test