name: setup-fastlane
run-name: Setup Fastlane

on:
  workflow_call:

jobs:
    setup-fastlane:
        name: Setup Fastlane
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'
          - name: Grant execute permission for gradlew
            run: chmod +x ./gradlew
          - name: Setup Ruby
            run: |
              sudo apt-get update
              sudo apt-get install -y ruby-full ruby-bundler build-essential
              gem install bundler